### ISSUE TITLE
allow st2_revision to be set to 'latest'

### ISSUE THREAD

**Issue by AndyMoore111** [StackStorm/ansible-st2#142]
we'll probably have to pin to a specific version of stackstorm, but the revision is less important for us.

It'd be good to be able to set st2_version=2.2.1 st2_revision=latest to pin at whatever the latest 2.2.1 release is without having to know the exact revisions that've been released in advance

**Comment by AndyMoore111** [comment]
duplicate of https://github.com/StackStorm/ansible-st2/issues/111

**Comment by armab** [comment]
Thanks for noticing #111!
In a meantime, we welcome contributions ;)
