### ISSUE TITLE
'st2_version' Overhaul

### ISSUE THREAD

**Issue by armab** [StackStorm/ansible-st2#150]
The goal is consistent functionality incl. naming when it comes to specifying Stackstorm version to install to allow users achieve what they want: major/minor/path version, auto-update, no-autoupdate, latest revision pin, etc.

- [x] Fix version install syntax for `apt`/`yum` (done in https://github.com/StackStorm/ansible-st2/pull/148/commits/dfb5588d57d2cfc390e73a1f226ffd8514d0ce77)
- [ ] Consider deprecating `st2_revision` since it doesn't work everywhere
  - `apt install st2=2.2.1-5` (revision is required)
  - `yum install st2-2.2.1` (revision could be omitted)
- [ ] Consistency: not every role contains `st2_revision`. Use everywhere or nowhere.
- [ ] Naming overhaul for `st2_version`: `null`, ``, `latest`, `present`, `*`
- [ ] Consider changing `st2_version` defaults to NO auto-update, as prod-friendly setting
- [ ] Research solution for https://github.com/StackStorm/ansible-st2/issues/111
- [ ] Better README with version install examples & tricks & describing diff apt/yum behavior to allow users achieve what they want (stable, patch, auto-update, no-autoupdate, latest revision pin)

**Comment by AndyMoore** [comment]
have just raised https://github.com/StackStorm/ansible-st2/pull/159 to improve the documentation around the current situation

at the moment if you pin st2_version you must also pin mistral_version - when the above is done it'd be great if pinning stackstorm_version would do both st2 and st2mistral

also currently the way these are currently defined is different:

`/etc/ansible/roles/stackstorm/roles/st2/tasks/main.yml:    name: st2{{ '-' if ansible_pkg_mgr == 'yum' else '=' }}{{ st2_version }}-{{ st2_revision }}
/etc/ansible/roles/stackstorm/roles/st2mistral/tasks/main.yml:    name: st2mistral{{ '-' if ansible_pkg_mgr == 'yum' else '=' }}{{ st2mistral_version }}`

st2 has a revision whereas st2mistral has it as part of the version
