### ISSUE TITLE
commit '30b964bc80149c447e98397bd2f977b368b7431b' is breaking  st2web role

### ISSUE THREAD

**Issue by amila-ku** [StackStorm/ansible-st2#152]
commit '30b964bc80149c447e98397bd2f977b368b7431b' in ansible-st2/roles/st2web/handlers/main.yml is invalid it should have ansible handlers like 

------------------------
```
-- name: restart nginx		
 -  become: yes		
 -  service:		
 -    name: nginx		
 -    state: restarted
```

------------------------

instead it has a entire play

-------------------------
name: ensure st2web logs permissions
```
 +  become: yes
 +  file:
 +    path: "{{ item }}"
 +    mode: "o-r"
 +  with_fileglob:
 +    - "/var/log/nginx/st2webui.*"
 +    - "/var/log/nginx/ssl-st2webui.*"
 +  listen:
 +    - start nginx
 +    - restart nginx
```

**Comment by amila-ku** [comment]
this was due to using ansible 2.1

**Comment by armab** [comment]
Right, keep in mind that we assume minimum Ansible 2.2 version here:

https://github.com/StackStorm/ansible-st2/blob/master/roles/st2web/meta/main.yml#L7

**Comment by amila-ku** [comment]
thanks, found a workaround.
