### ISSUE TITLE
st2 role: config option actionrunner.virtualenv_opts leaves duplicate entry

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/ansible-st2#166]
This might be an issue with the ini_file ansible module, but I came up blank when I googled about.

It seems that there is already an empty entry for `actionrunner.virtualenv_opts` in the default st2.conf file.
After setting virtualenv_opts with the ansible task, it leaves the original empty option, and adds a new one. I think it should update the original one, or at least remove the original after adding the new one.

```
[actionrunner]
logging = /etc/st2/logging.actionrunner.conf
virtualenv_opts =
vritualenv_opts = --always-copy,--system-site-packages
```

Any idea why this is happening, or how to clean it up automatically?

**Comment by armab** [comment]
You have a typo.

Compare `virtualenv_opts` vs `vritualenv_opts`

**Comment by cognifloyd** [comment]
I looked at that so many times and didn't see the typo. This is not a bug, it's a typo. :+1:
