### ISSUE TITLE
Run `systemctl daemon-reload` on update

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/ansible-st2#169]
I just upgraded a stackstorm install with the playbook (from 2.3 to 2.4) and when I was manually looking at some issues with st2chatops, I got this:

```
# systemctl stop st2chatops
Warning: st2chatops.service changed on disk. Run 'systemctl daemon-reload' to reload units.
```

It looks like we might need to run systemctl daemon-reload somewhere after installing these packages, at least on EL 7. (I'm using CentOS 7)

**Comment by armab** [comment]
Agree, but this should be better automated as part of the `deb`/`rpm` packaging and not Ansible.

This affects both Ubuntu16 and CentOS7 with systemd.
Similar requests in other software:
- https://jira.mariadb.org/browse/MDEV-11045
- https://github.com/kubernetes/release/issues/98

Can you please submit issue in https://github.com/stackstorm/st2-packages instead?

**Comment by armab** [comment]
Closing in favor of https://github.com/StackStorm/st2-packages/issues/495
