### ISSUE TITLE
Ensure that the chatops api key still exists on re-run

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/ansible-st2#176]
I ran the playbook, did some testing, and dropped the database (with an `st2ctl reload`) once I was ready to use it in production. I didn't think about how that would also delete the api keys, which `st2ctl reload`, of course, can't recover.

Let's add some error checking to query st2 and make sure the api key in st2chatops.env still exists. If it doesn't then we still need to add it.

**Comment by armab** [comment]
This could be controversial change, depending on user's needs.

If user dropped the database, - of course it's expected that all StackStorm data related to keys, tokens or K/V storage is gone.

Checking that StackStorm API key is inserted into `st2chatops.env` and is still valid on every Ansible run looks like redundant to me. That's another several calls and there are corner cases to handle with multi-node deployments. Such logic IMO is a good place for Infrastructure tests user may have after provision is done (ex: optional `st2smoketests` does that).

This is similar if by some reason `HUBOT_SLACK_TOKEN` inserted into `st2chatops.env` is revoked. It could be not expected from the role to check token validity every time on Ansible run, but might be a good place for some smoke-tests which are executed post-run.

----

After all, if API token in `st2chatops.env` is invalid, - service `st2chatops` will fail to start and user will be aware of that when the role is executed which looks good enough for now, talking about simplicity <> complexity balance.
Though, there is always a room to reconsider it in future.
