### ISSUE TITLE
st2smoketests failure when using proxies

### ISSUE THREAD

**Issue by sammic30** [StackStorm/ansible-st2#178]
This TASK is failing, please see details below:

```bash
TASK [st2smoketests : Install st2 pack from exchange] **********************************************************************************************************************************************************************************************
task path: /root/ansible-st2/roles/st2smoketests/tasks/main.yml:44
Using module file /root/ansible/lib/ansible/modules/commands/command.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1507238390.43-266056893469963 `" && echo ansible-tmp-1507238390.43-266056893469963="` echo /root/.ansible/tmp/ansible-tmp-1507238390.43-266056893469963 `" ) && sleep 0'
<localhost> PUT /tmp/tmp2hNas5 TO /root/.ansible/tmp/ansible-tmp-1507238390.43-266056893469963/command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1507238390.43-266056893469963/ /root/.ansible/tmp/ansible-tmp-1507238390.43-266056893469963/command.py && sleep 0'
<localhost> EXEC /bin/sh -c 'ST2_AUTH_TOKEN=d80cbedd7eab4ab08ac5a58a382695d2 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1507238390.43-266056893469963/command.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1507238390.43-266056893469963/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "cmd": [
        "st2",
        "pack",
        "install",
        "st2"
    ],
    "delta": "0:00:00.316119",
    "end": "2017-10-05 21:19:50.859144",
    "failed": true,
    "invocation": {
        "module_args": {
            "_raw_params": "st2 pack install st2",
            "_uses_shell": false,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2017-10-05 21:19:50.543025",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "ERROR: 400 Client Error: Bad Request\nMESSAGE: No results from the index: tried https://index.stackstorm.org/v1/index.json.\nStatus: [\n    {\n        \"url\": \"https://index.stackstorm.org/v1/index.json\", \n        \"message\": \"SSLError(SSLError(SSLError(\\\"bad handshake: SysCallError(104, 'ECONNRESET')\\\",),),)\", \n        \"error\": \"unresponsive\", \n        \"packs\": 0\n    }\n] for url: http://127.0.0.1:9101/v1/packs/index/search",
    "stdout_lines": [
        "ERROR: 400 Client Error: Bad Request",
        "MESSAGE: No results from the index: tried https://index.stackstorm.org/v1/index.json.",
        "Status: [",
        "    {",
        "        \"url\": \"https://index.stackstorm.org/v1/index.json\", ",
        "        \"message\": \"SSLError(SSLError(SSLError(\\\"bad handshake: SysCallError(104, 'ECONNRESET')\\\",),),)\", ",
        "        \"error\": \"unresponsive\", ",
        "        \"packs\": 0",
        "    }",
        "] for url: http://127.0.0.1:9101/v1/packs/index/search"
    ]
}
```
I'm running `ansible-playbook stackstorm.yml -i 'localhost,' --connection=local` and st2 version is 2.4.1

I was able to download "https://index.stackstorm.org/v1/index.json" via wget

**Comment by LindsayHill** [comment]
@sammic30 your failures are almost certainly because you are using a proxy. Can you please add those details here?

**Comment by sammic30** [comment]
Yea, I don't have internet access and I'm using proxy as ENV variables, like below:
export http_proxy=http://proxy-server.com:8080
export https_proxy=http://proxy-server.com::8080

**Comment by LindsayHill** [comment]
What happens if you manually run commands like `st2 pack install st2`?

What OS/version are you using?

Did the playbooks create the st2api & st2actionrunner files described here? https://docs.stackstorm.com/packs.html#installing-packs-from-behind-a-proxy

**Comment by sammic30** [comment]
I'm using Ubuntu-16.04 (Xenial).  st2api & st2actionrunner files are not created by playbook.

------ Output------

ERROR: 400 Client Error: Bad Request
MESSAGE: No results from the index: tried https://index.stackstorm.org/v1/index.json.
Status: [
    {
        "url": "https://index.stackstorm.org/v1/index.json",
        "message": "SSLError(SSLError(SSLError(\"bad handshake: SysCallError(104, 'ECONNRESET')\",),),)",
        "error": "unresponsive",
        "packs": 0
    }
] for url: http://127.0.0.1:9101/v1/packs/index/search

Also, I chnaged https -- http for this Web UI task b'coz that was filing with https

- name: Check web-ui is up
  uri:
    url: http://localhost/
    validate_certs: no
  changed_when: no
  tags:
    - smoke-tests

**Comment by LindsayHill** [comment]
What failures were you getting with the Web UI check? Is anything listening on https://localhost?

**Comment by sammic30** [comment]
TASK [st2smoketests : Check web-ui is up] **********************************************************************************************************************************************************************************************************
task path: /root/ansible-st2/roles/st2smoketests/tasks/main.yml:36
Using module file /root/ansible/lib/ansible/modules/net_tools/basics/uri.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1507246091.27-155535911598615 `" && echo ansible-tmp-1507246091.27-155535911598615="` echo /root/.ansible/tmp/ansible-tmp-1507246091.27-155535911598615 `" ) && sleep 0'
<localhost> PUT /tmp/tmpcnByhw TO /root/.ansible/tmp/ansible-tmp-1507246091.27-155535911598615/uri.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1507246091.27-155535911598615/ /root/.ansible/tmp/ansible-tmp-1507246091.27-155535911598615/uri.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1507246091.27-155535911598615/uri.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1507246091.27-155535911598615/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_JSjn4k/ansible_module_uri.py", line 468, in main
    uresp['location'] = absolute_location(url, uresp['location'])

fatal: [localhost]: FAILED! => {
    "changed": false,
    "content": "",
    "failed": true,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "body": null,
            "body_format": "raw",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "creates": null,
            "delimiter": null,
            "dest": null,
            "directory_mode": null,
            "follow": false,
            "follow_redirects": "safe",
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": {},
            "http_agent": "ansible-httpget",
            "method": "GET",
            "mode": null,
            "owner": null,
            "regexp": null,
            "remote_src": null,
            "removes": null,
            "return_content": false,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "status_code": [
                200
            ],
            "timeout": 30,
            "unsafe_writes": null,
            "url": "https://localhost/",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": false
        }
    },
    "msg": "Status code was not [200]: Request failed: <urlopen error Tunnel connection failed: 503 Service Unavailable>",
    "redirected": false,
    "status": -1,
    "url": "https://localhost/"
}

**Comment by LindsayHill** [comment]
Ignoring Ansible for now, is anything listening on port 443 on your VM? What happens if you try to do something like `curl -v -k https://localhost`? Does that work? (If you do have proxy environment variables, make sure you have `no_proxy` settings for localhost, etc., so it doesn't try to use the proxy).

Also, can you please format your posts using Github Markdown? Makes it much easier to read code output. You can see where I've edited your earlier posts here

**Comment by sammic30** [comment]
```
* Rebuilt URL to: https://localhost/
*   Trying ::1...
* connect to ::1 port 443 failed: Connection refused
*   Trying 127.0.0.1...
* connect to 127.0.0.1 port 443 failed: Connection refused
* Failed to connect to localhost port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 443: Connection refused
```
I believe this is causing the issue... 443 connection refused

**Comment by LindsayHill** [comment]
Is anything listening on port 443 on your VM? 
Run `sudo netstat -ntlp`. What does that report?

**Comment by LindsayHill** [comment]
You can also check your nginx configuration. Normally there is a section in `/etc/nginx/conf.d/st2.conf` for 443/SSL.

**Comment by LindsayHill** [comment]
The web ui test failures above are due to other webservers running on that system. 

There does still appear to be a proxy-related issue though.

**Comment by sammic30** [comment]
Thanks looks like the issue is resolved... I opened the port 443 and killed the apache2 service and now the playbook is successful.

output of curl command after port 443 is accessible.

```
curl -v -k https://localhost
* Rebuilt URL to: https://localhost/
*   Trying ::1...
* connect to ::1 port 443 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 694 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: st2-192219764-1-273290998 (does not match 'localhost')
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.12.1
< Date: Fri, 06 Oct 2017 21:24:53 GMT
< Content-Type: text/html
< Content-Length: 1328
< Last-Modified: Tue, 12 Sep 2017 19:53:24 GMT
< Connection: keep-alive
< Front-End-Https: on
< X-Content-Type-Options: nosniff
< Accept-Ranges: bytes
<
<!doctype html>
<html lang="en" ng-app="main" ng-controller="MainCtrl">
<head>
  <meta charset="utf-8">
  <title ng-bind="state.current.title"></title>

  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
  <link rel="icon" href="favicon.ico" type="image/x-icon">

  <!-- buils:styles -->
  <link rel="stylesheet" href="css/style.css">
  <!-- endbuild -->

  <!-- reamaze -->
  <script type="text/javascript" src="https://d3itxuyrq7vzpz.cloudfront.net/assets/reamaze.js"></script>
  <script type="text/javascript">
    var _support = _support || { 'ui': {}, 'user': {} };
    _support['account'] = 'stackstorm';
    _support['ui']['lightbox_mode'] = 'kb';
  </script>
  <!-- end:reamaze -->

  <script src="node_modules/angular/angular.js"></script>
  <script src="node_modules/lodash/dist/lodash.js"></script>
  <script src="node_modules/st2client/dist/st2client.js"></script>
  <script src="node_modules/react/dist/react.js"></script>
  <script src="node_modules/react-dom/dist/react-dom.js"></script>
  <script src="node_modules/ngreact/ngReact.js"></script>
  <script src="js/dependencies.js"></script>
  <script src="js/modules.js"></script>
  <script src="js/apps.js"></script>
  <script src="js/main.js"></script>
  <script src="config.js"></script>
</head>

<body>
  <div ui-view></div>
</body>

</html>
* Connection #0 to host localhost left intact
```

**Comment by LindsayHill** [comment]
Are you still having problems with `st2 pack install st2`?

**Comment by sammic30** [comment]
I didn't face the ```st2 pack install st2``` error in new installation.
