### ISSUE TITLE
nginx web doesnt start due to spacing issue in nginx.conf file

### ISSUE THREAD

**Issue by bhudlemeyer** [StackStorm/ansible-st2#184]
nginx.conf file has incorrect spacing for include /etc/nginx/sites-enabled/*; setting. This causes nginx to ignore sites-enabled.

![image](https://user-images.githubusercontent.com/2275490/33233351-432ffd02-d1d2-11e7-95e2-f85b9573df2b.png)

both includes should be same level of indent. 

file that needs to be moded
 ansible-st2/roles/nginx/tasks/main.yml

**Comment by armab** [comment]
Thanks! 
Knowing the fix, - would be nice to see a PR next :+1: 


----

Out of curiosity, what `nginx` version you had on your system and OS?

Surprising that the same config works on: 
```
Ubuntu xenial
nginx/1.12.2
```

**Comment by bhudlemeyer** [comment]
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

nginx -v
nginx version: nginx/1.12.2

**Comment by bhudlemeyer** [comment]
Pull request opened to resolve bug   https://github.com/StackStorm/ansible-st2/pull/185
