### ISSUE TITLE
Documentation of testu / testp

### ISSUE THREAD

**Issue by candlerb** [StackStorm/ansible-st2#189]
After installing stackstorm following [the ansible instructions](https://docs.stackstorm.com/install/ansible.html), I found I could not login with the default `st2admin` / `Ch@ngeMe` as documented in [several](https://docs.stackstorm.com/start.html) [places](https://docs.stackstorm.com/authentication.html)

It turns out after checking `/etc/st2/htpasswd` that the default username is `testu`, and the default password is `testp`

I think this would be worth a mention on the ansible installation instructions page.

**Comment by armab** [comment]
In `ansible-st2` repo there are `Variables` section containing `st2_auth_username` and `st2_auth_password` descriptions with their defaults.

But indeed, https://docs.stackstorm.com/install/ansible.html is missing a mention about default login credentials used.

Thanks for the report!
