### ISSUE TITLE
Ansible 2.4+ deprecation warnings

### ISSUE THREAD

**Issue by armab** [StackStorm/ansible-st2#190]
Fix Ansible deprecation warnings starting to appear since Ansible `2.4`: 
```
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 
'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.
 This feature will be removed in a future release. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is
 discouraged. The module documentation details page may explain more about this
 rationale.. This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

**Comment by cognifloyd** [comment]
`import_tasks` and `include_tasks` require ansible 2.4 and up.
`include` was set to be deprecated in [ansible 2.8](https://github.com/ansible/ansible/blob/8799038a895ed0ff230e2aa0629c4b83e8f15cf1/lib/ansible/modules/utilities/logic/_include.py#L22), but that has been [delayed](https://github.com/ansible/ansible/commit/4dcc5588f695dba5a04dfc4ebdbb73818a255f51#diff-fa05a7dabb0c43b34ba1eeb3464bd2a2):
> defering deprecation until we are comfortable that the new actions
> cover most of the ground users need.

If we're ready to require ansible 2.4 minimum then we can get rid of the deprecation notices. I would love to require ansible 2.4 as I already require it for the playbooks I write. But, I don't know if that would be a generally acceptable requirement yet.

**Comment by armab** [comment]
@cognifloyd That's a perfectly valid point, agree with you :+1: 

So yeah, Ansible 2.5 is just out.
Considering that currently we set minimum `2.2` requirement in roles, probably pumping requirements to `2.4` would be too much an aggressive move.

Will wait for a couple of Ansible releases for things to settle down and users move to new versions, before making this change.

**Comment by cognifloyd** [comment]
:tada: Ansible 2.6 is here. https://groups.google.com/forum/#!topic/ansible-announce/JI1Zju5x3TA

It's got lots of bugfixes for include* and import*.

Current ansible [support matrix](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html) for 2.2 and above has not been updated to account for the release of 2.6:

Ansible Release | Latest Version | Status
-- | -- | --
devel | 2.6 (unreleased, trunk) | In development
2.5 | 2.5.4 (2018-05-31) | Supported (security and general bugfixes)
2.4 | 2.4.4 (2018-01-31) | Supported (security and critical bug fixes)
2.3 | 2.3.3 (2017-12-20) | Unsupported (end of life)
2.2 | 2.2.3 (2017-05-09) | Unsupported (end of life)

When 2.4 was released it looked like this:

Ansible Release | Latest Version | Status
-- | -- | --
devel | 2.5 (unreleased, trunk) | In development
2.4 | 2.4.x (2017-09-19) | Supported (bug and security fixes)
2.3 | 2.3.2 (2017-08-08) | Supported (bug and security fixes)
2.2 | 2.2.3 (2017-05-09) | Supported (only security fixes)

So, I'd love to bump the minimum if that's ok. How high can we push it? If not now, when?

**Comment by LindsayHill** [comment]
Good stuff. Looks like it's also time for us to tag another release? 0.9.0 maybe?

**Comment by armab** [comment]
Yep, the plan is also to include https://github.com/StackStorm/ansible-st2/issues/207 fix in that upcoming release.

**Comment by armab** [comment]
Alright, I've finished #207 to fix the build.
Will wait for @cognifloyd to include the changes with min Ansible version and deprecation notices and we can release the new version early next week.

**Comment by armab** [comment]
I've released https://github.com/StackStorm/ansible-st2/releases/tag/v0.9.0 as there were _really_ enough of other unreleased changes. For better convenience, that will be last release supporting old Ansible `v2.3` so people could pin to it if they want.

I'm good if we bump min Ansible to `v2.5` and call it next dedicated release (which could be done anytime ASAP) so @cognifloyd if you want to look at those changes, - that would be welcomed :+1: 

Having this Ansible transition tagged as a new release I think would be better and easier for us & community.
