### ISSUE TITLE
Add support for NodeJS v10

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/ansible-st2#194]
StackStorm/st2chatops#109

**Tasks**
- Wait for NodeJS v10 to be supported upstream in StackStorm/st2chatops
- Edit https://github.com/StackStorm/ansible-st2/blob/master/roles/nodejs/defaults/main.yml to install v10 
- Test installation in various platforms

**Comment by armab** [comment]
Seems NodeJS was hard-migrated to `v10` via https://github.com/StackStorm/ansible-st2/commit/223e786fe90a967551427de0eece17e41c153158
