### ISSUE TITLE
Rename BWC -> EWC

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/ansible-st2#220]
When reviewing the install steps for Enterprise components i notice that there are still references to BWC that should be renamed to EWC.

**Comment by armab** [comment]
Just a note, - renaming `bwc` -> `ewc` role and its variables will be a breaking change and so it'll need to be released properly.

**Comment by LindsayHill** [comment]
Maybe time for us to tag a 1.0.0 release with that change?

**Comment by armab** [comment]
Good timing for that idea :+1:
