### ISSUE TITLE
StackStorm.st2 "msg": "No package matching 'st2' is available"

### ISSUE THREAD

**Issue by sammic30** [StackStorm/ansible-st2#241]
Hi, I'm trying to install St2 using ansible and facing many issues b'coz of firewalls (I believe), few of them I resolved already and now facing this new issue below, Can anyone please provide a work around or permanent solution?

TASK [StackStorm.st2 : Install latest st2 package, auto-update] *************************************************************************************************************************************************************************************************
task path: /data/ansible-st2/roles/StackStorm.st2/tasks/main.yml:14
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1557961966.34-63228884919589 `" && echo ansible-tmp-1557961966.34-63228884919589="` echo /root/.ansible/tmp/ansible-tmp-1557961966.34-63228884919589 `" ) && sleep 0'
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/packaging/os/apt.py
<localhost> PUT /root/.ansible/tmp/ansible-local-18814_BSstv/tmpGXzFNa TO /root/.ansible/tmp/ansible-tmp-1557961966.34-63228884919589/AnsiballZ_apt.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1557961966.34-63228884919589/ /root/.ansible/tmp/ansible-tmp-1557961966.34-63228884919589/AnsiballZ_apt.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1557961966.34-63228884919589/AnsiballZ_apt.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1557961966.34-63228884919589/ > /dev/null 2>&1 && sleep 0'
FAILED - RETRYING: Install latest st2 package, auto-update (5 retries left).Result was: {
    "attempts": 1,
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false,
            "autoclean": false,
            "autoremove": false,
            "cache_valid_time": 0,
            "deb": null,
            "default_release": null,
            "dpkg_options": "force-confdef,force-confold",
            "force": false,
            "force_apt_get": false,
            "install_recommends": null,
            "name": "st2",
            "only_upgrade": false,
            "package": [
                "st2"
            ],
            "purge": false,
            "state": "latest",
            "update_cache": null,
            "upgrade": null
        }
    },
    "msg": "No package matching 'st2' is available",
    "retries": 6
}

**Comment by armab** [comment]
As replied in https://forum.stackstorm.com/t/stackstorm-st2repo-add-keys-to-keyring/652

You need to have access to packagecloud.io, otherwise you'll be unable to add the APT repository and download StackStorm packages. There is no workaround.

Alternative solution is to use different deployment method if you're behind firewalls/proxy. For example, Virtual Appliance/OVA which already has preinstalled StackStorm system and ready to be downloaded as artifact https://docs.stackstorm.com/install/vagrant.html
