### ISSUE TITLE
Ansible 2.8? pyvcloud?

### ISSUE THREAD

**Issue by ivanmpk** [StackStorm/ansible-st2#245]
Is there road map to use ansible 2.8 in this pack?

How to include pyvcloud in this pack?

**Comment by LindsayHill** [comment]
This is not a pack. It's a role to install StackStorm. It works fine with Ansible 2.8. Are you having problems?

**Comment by LindsayHill** [comment]
> How to include pyvcloud in this pack?
It's better to keep unrelated questions in separate issues, makes it easier to track.

Are you perhaps thinking of the Ansible integration pack for StackStorm? https://github.com/StackStorm-Exchange/stackstorm-ansible

**Comment by ivanmpk** [comment]
Hi @LindsayHill sorry. It's a mistake. I will create new issue on github stackstorm pack about ansible.
