### ISSUE TITLE
Pass mongo user/passwd to role

### ISSUE THREAD

**Issue by nicholasamorim** [StackStorm/ansible-st2#247]
I use my own MongoDB, so I have a playbook that imports only certain roles.

Is there any way I can pass certain values to `st2.conf`? I'm mainly interested in the database user and password.

**Comment by armab** [comment]
See https://github.com/StackStorm/ansible-st2#variables `st2_config` which allows to do that.

**Comment by nicholasamorim** [comment]
Duh, that's true - I even use it already 🤦‍♂ .

Thanks for the prompt response!
