### ISSUE TITLE
Support for Ubuntu 18.04

### ISSUE THREAD

**Issue by gopivalleru** [StackStorm/ansible-st2#249]
I've ran ansible playbook for stackstorm on Ubuntu 18 which trowed multiple errors. Below are the changes I had to make to make installation work

Mongo DB changes to support 4.0:
StackStorm.mongodb/defaults/main.yml
mongodb_version: "4.0"
mongodb_apt_keys:
"3.2": "42F3E95A2C4F08279C4960ADD68FA50FEA312927"
"3.4": "0C49F3730359A14518585931BC711F9BA15703C6"
"4.0": "9da31620334bd75d9dcb49f368818c72e52529d4"

changed print command to python 3 compatible.
StackStorm.st2/tasks/version.yml
under task: Get installed st2 version
change command: /opt/stackstorm/st2/bin/python -c 'import st2common; print st2common.version'
to

command: /opt/stackstorm/st2/bin/python -c 'import st2common; print(st2common.version)'

Mistral is not supported on Ubuntu 18.04
comment or remove StackStorm.st2mistral role from stackstorm.yml role.

**Comment by armab** [comment]
Thanks for sharing that info!

Could you compose the PR that will implement some of these additions for Ubuntu 18?
