### ISSUE TITLE
EWC/Enterprise transition to OpenSource

### ISSUE THREAD

**Issue by armab** [StackStorm/ansible-st2#260]
Currently Ansible deployment provides functionality of installing EWC/Enterprise version.
There is a dedicated role for that: https://github.com/StackStorm/ansible-st2/tree/master/roles/StackStorm.ewc

As Extreme Networks open-sourced the EWC Enterprise (https://stackstorm.com/2020/05/27/extreme-networks-donates-ewc-to-linux-foundation/), remove the Enterprise functionality from the Ansible module. Rework the module so the settings like RBAC/LDAP could be still easily adjusted via `st2` role.

This could be done once the Enterprise functionality is integrated into core StackStorm code.

**Comment by amanda11** [comment]
From discussion on the November TSC meeting then RBAC would be disabled by default to ease upgrade for community users, but would need an option to enable as a parameter (to replace the licensekey parameter)

**Comment by armab** [comment]
:+1: 

Looking at the current Ansible variables config, I guess something along the lines:
```
st2_rbac:
  enable: yes
  roles: ...
  assignments: ...
```
or `st2_rbac_enable: yes`. Same for ldap.

Which will change the respective `st2.conf` settings.

**Comment by winem** [comment]
I'm working on a PR now.
