### ISSUE TITLE
For EL7 and U16, Install Mongo 4.0 (Ansible)

### ISSUE THREAD

**Issue by punkrokk** [StackStorm/ansible-st2#264]
While newer recently added platforms like Ubuntu18 and CentOS8 rely on MongoDB 4,
older systems like EL7 and U16 are still on MongoDB 3.4

MongoDB v3.4 has reached its EOL in January 2020.
~Switch to MongoDB v3.6 instead~, following the StackStorm/st2docs#968
Update: Switch to MongoDB `v4.0` across all the OSes, including EL7 and U16 as we found that's supported by Mongo.

See stackstorm/st2-packages#643 for the changes needed.

**Comment by amanda11** [comment]
Started on a PR...

**Comment by armab** [comment]
*Update:* Based on discussion in `#development` team decided to use MongoDB 4.0 across all the platforms.
Turns on previously Mongo 4 wasn't supported for EL7 and U16.
This will guarantee consistency in Mongo version everywhere and less code hacks in installers.
