### ISSUE TITLE
Drop EL6 support

### ISSUE THREAD

**Issue by armab** [StackStorm/ansible-st2#267]
Per Roadmap (https://docs.stackstorm.com/roadmap.html#id1), `CentOS 6` / `RHEL 6` will be fully deprecated and removed in `v3.3.0` release.

It's a great time to remove all the EL6 installer hacks we had during this years :)

**Comment by amanda11** [comment]
Happy to take this on after the mongodb 4.0 changes, will touch alot of the files I changed for adding RH 8 support.
