### ISSUE TITLE
Deprecate Mistral

### ISSUE THREAD

**Issue by armab** [StackStorm/ansible-st2#270]
> Part of [ Mistral Deprecation Game Plan](https://github.com/StackStorm/st2/issues/4762)

Closes https://github.com/StackStorm/ansible-st2/issues/95
Closes https://github.com/StackStorm/ansible-st2/issues/112 

Per roadmap we deprecate Mistral in `v3.3.0`.
This should be a fun task to remove all the `mistral` and `postgresql` logic from the Ansible deployment.

**Comment by amanda11** [comment]
I'll take this on.
