### ISSUE TITLE
`st2web_package_name` is undefined

### ISSUE THREAD

**Issue by mamercad** [StackStorm/ansible-st2#316]
After pinning `st2web_version: 3.7.0-1`, I get the following error:

```
    The task includes an option with an undefined variable. The error was: 'st2web_package_name' is undefined
  
    The error appears to be in '/Users/mmercado/src/[redacted]/ansible-st2/roles/StackStorm.st2web/tasks/main.yml': line 26, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: Install pinned st2web package
      ^ here
```

Initially, I had it unset (so, presumably defaulted to `stable`). On my second run, I decided to pin the version and hit the error above.

**Comment by amanda11** [comment]
You can specify the st2web_package_name in your top-level variables to get round this. But this really should be in role/st2web/defaults/main.yml and set to "st2web".
Or event we probably don't need the variable anymore, as its a legacy from when we had st2web and st2flow.

We welcome PRs from the community, if you'd like to submit a change to resolve.
