### ISSUE TITLE
Could we get a new release?

### ISSUE THREAD

**Issue by mamercad** [StackStorm/ansible-st2#324]
It has been a while since the last release, could we get a new one? I'm in the process of building a [DigitalOcean 1-Click App](https://docs.digitalocean.com/glossary/one-click/) of StackStorm and I'm trying to pin as many versions as possible. I had this repository pinned at `v3.1.0` and it doesn't have [this](https://github.com/StackStorm/ansible-st2/blob/master/roles/StackStorm.st2/tasks/version.yml) fix, and likely a few more. Thanks in advance!

**Comment by armab** [comment]
v3.2.0 is released: https://github.com/StackStorm/ansible-st2/releases/tag/v3.2.0

Thanks for the issue! We totally forgot about it.

**Comment by mamercad** [comment]
> v3.2.0 is released: https://github.com/StackStorm/ansible-st2/releases/tag/v3.2.0
> 
> Thanks for the issue! We totally forgot about it.

Oh sweet, thank you!
