### ISSUE TITLE
Literal version lookup fails

### ISSUE THREAD

**Issue by rjmackay** [StackStorm/ansible-st2#36]
The "Lookup literal version" task is failing silently with "sort: unrecognized option `--version-sort'"
Leaving _st2_version set to "" and breaking following tasks

**Comment by rjmackay** [comment]
I'm attempted to install on an Ubuntu 14.04.2 server on Rackspace. It has sort (GNU coreutils) 8.21, which doesn't have the --version-sort argument

**Comment by dzimine** [comment]
Thanks for reporting @rjmackay !
We'll are happy to take a PR if you will :) Or we will look at it as we got a cycle to fix it.

**Comment by rjmackay** [comment]
Ah figured it out. Its delegating to localhost for that task. Given my local is OSX it doesn't have the standard GNU sort. Should be an easy fix I think
