### ISSUE TITLE
Must set log directory permissions to system user

### ISSUE THREAD

**Issue by j3p0uk** [StackStorm/ansible-st2#39]
After an ansible install from https://docs.stackstorm.com/install/ansible.html on a fresh ubuntu 14.04 vm none of the st2 services were started.  This is because /var/log/st2 was owned by root:root, and needed to be owned by stanley:stanley ({{ st2_system_user }}).

**Comment by armab** [comment]
Thanks @j3p0uk for the report. I'm sorry that happened.

We're currently on hard work rebuilding entire installation story where pip requirements/virtualenv are bundled into package and such things like `chown` will be totally controlled by packaging and not by configuration management tool like Ansible/Puppet/Chef/etc.

So entire Ansible provision logic will be reworked once we publish new packages into production. It'll happen soon.
At the same time, better testing engine and more platforms will be added for Ansible playbooks (outside of current Ubuntu trusty).
