### ISSUE TITLE
virtualenv is not installed

### ISSUE THREAD

**Issue by armab** [StackStorm/ansible-st2#40]
As reported in: https://github.com/StackStorm/st2contrib/issues/421

**Comment by mtarvainen** [comment]
Is there any progress in sight for fixing this issue? It currently cripples [st2-chatops-aliases](https://github.com/armab/st2-chatops-aliases/) package. I'm running Stackstorm version 1.3.2.16 from AIO installer.

**Comment by armab** [comment]
@mtarvainen Thanks for you message.

* `AIO` installer is considered as outdated (we'll add deprecation notice, see https://github.com/StackStorm/st2docs/issues/110)
* `ansible-st2` is considered as outdated (there is deprecation notice)
* The recommended way (`deb`/`rpm` packages) of installing StackStorm is:
  * [Ubuntu/Debian](https://docs.stackstorm.com/install/deb.html)
  * [RHEL7/CentOS7](https://docs.stackstorm.com/install/rhel7.html)
  * [RHEL6/CentOS6](https://docs.stackstorm.com/install/rhel6.html)

The effort for the moment is focused on new `deb`/`rpm` packages, meaning no fixes in `AIO`.

Sorry for confusion.

**Comment by mtarvainen** [comment]
@armab thanks for your fast reply!

I tried package installation and that worked it out! Now Ansible (including [st2-chatops-aliases](https://github.com/armab/st2-chatops-aliases/)) works as expected.
