### ISSUE TITLE
Ansible playbook needs an update

### ISSUE THREAD

**Issue by murgurgula** [StackStorm/ansible-st2#43]
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default). This feature will be removed in a future release. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
--
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{postgresql_env}}'). This feature 
will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

**Comment by armab** [comment]
Part of: https://github.com/StackStorm/ansible-st2/issues/38

Also FYI current Ansible playbooks are considered as outdated,
see Notice in [README.md](https://github.com/StackStorm/ansible-st2/blob/master/README.md)

Rewrite for new packages is required, some work is done in: #42

**Comment by murgurgula** [comment]
Sorry for the repetitive ticket. I somehow managed to not see the elefant in the room.

**Comment by armab** [comment]
No problem with that,
something not working is really our fault :cactus:

**Comment by murgurgula** [comment]
It's opensource, it's everyone's fault ^_^ :heart:

However, I would really like to see this updated. I need quick provisioning, so if all stackstorm VM fail in our prod, the oncall person could just launch a script and get them magically up and running as before. 
Having a working st2 ansible repo would be a great base for that purpose.

Also, the current st2-ansible does not have the st2web package. It would be usefull to add it.
