### ISSUE TITLE
Refactor st2web [EL]

### ISSUE THREAD

**Issue by armab** [StackStorm/ansible-st2#77]
- [x] Tag all tasks in role
- [x] Update meta file
- [x] EL support
  - [x] CentOS6
  - [x] RHEL6
  - [x] CentOS7
  - [x] RHEL7
- [x] Idempotence check
- [ ] New parameters to pass to `st2web` like `hostname`
  - [ ] Update README.md

**Comment by humblearner** [comment]
https://github.com/StackStorm/ansible-st2/pull/87
